namespace: robot1 # Namespace of the robot

pubs:
  - name: pub_twist # Variable name to use in code
    topic: /control/cmd_vel # Topic name relative to namespace
    msg_file: geometry_msgs.msg # ROS Message file to import type from
    msg_type: Twist # ROS Message type
  - name: pub_drive_mode
    topic: /control/set_drive_mode
    msg_file: std_msgs.msg
    msg_type: String

subs:
  - name: msg_odom
    topic: /odometry_local
    msg_file: nav_msgs.msg
    msg_type: Odometry
  - name: msg_gps
    topic: /ublox_gps_node/fix
    msg_file: sensor_msgs.msg
    msg_type: NavSatFix
  - name: msg_blob_cmd
    topic: /blob/cmd_vel
    msg_file: geometry_msgs.msg
    msg_type: Twist
  - name: msg_imu
    topic: /imu/data_raw
    msg_file: sensor_msgs.msg
    msg_type: Imu
  - name: msg_navheading
    topic: /navheading
    msg_file: sensor_msgs.msg
    msg_type: Imu
  - name: msg_navrelposned
    topic: /navrelposned
    msg_file: ublox_msgs.msg
    msg_type: NavRELPOSNED9
  - name: msg_front
    topic: /region/front/closest
    msg_file: std_msgs.msg
    msg_type: Float32
  - name: msg_frontleft
    topic: /region/frontleft/closest
    msg_file: std_msgs.msg
    msg_type: Float32
  - name: msg_frontright
    topic: /region/frontright/closest
    msg_file: std_msgs.msg
    msg_type: Float32
  - name: msg_rear
    topic: /region/rear/closest
    msg_file: std_msgs.msg
    msg_type: Float32
  - name: msg_pothole
    topic: /pothole/detection
    msg_file: std_msgs.msg
    msg_type: Float32
  - name: msg_drive_mode
    topic: /control/drive_mode
    msg_file: std_msgs.msg
    msg_type: String

service_calls: # ROS Service calls
  - name: srv_yolo # Name of client. Request is this name + _req
    topic: /detect_object
    msg_file: route_yolo_service.srv
    msg_type: DetectObject
