namespace: robot1 # Namespace of the robot

pubs:
  - name: pub_twist # Variable name to use in code
    topic: /cmd_vel # Topic name relative to namespace
    msg_file: geometry_msgs.msg # ROS Message file to import type from
    msg_type: Twist # ROS Message type

subs:
  - name: msg_odom
    topic: /odometry_local
    msg_file: nav_msgs.msg
    msg_type: Odometry
  - name: msg_gps
    topic: /ublox/fix
    msg_file: sensor_msgs.msg
    msg_type: NavSatFix

service_calls: # ROS Service calls
  - name: srv_yolo # Name of client. Request is this name + _req
    topic: /detect_object
    msg_file: route_yolo_service.srv
    msg_type: DetectObject
